---
version: '3'
services:
  api:
    build: .
    restart: always
    cap_add:
      - NET_ADMIN
    environment:
      - THERMOMETER_MAC_ADDR=CC:0C:40:6F:1F:19
      - HUMAN_DETECTOR_MAC_ADDR=EF:DA:4A:BE:E0:D1
      - PERIOD=10

